version: "3.6"

services:
  certman:
    image: quay.io/chimanlei/certman:0.1.0
    ports:
      - 2300:2300
    depends_on:
      - certmandb
    command: [ "hanami", "server" ]
    # entrypoint: /bin/sh
    # stdin_open: true
    # tty: true
  certmandb:
    image: mcr.microsoft.com/mssql/server:2019-CU19-ubuntu-20.04
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: mssql.certman0
      MSSQL_DATABASE: certman
    working_dir: /home/app
    volumes:
      - dev_certmandb:/var/opt/mssql
      - ./scripts:/home/app
  certmandb.test:
    image: mcr.microsoft.com/mssql/server:2019-CU19-ubuntu-20.04
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: mssql.certman0
      MSSQL_DATABASE: certman
    working_dir: /home/app
    volumes:
      - test_certmandb:/var/opt/mssql
      - ./scripts:/home/app

volumes:
  dev_certmandb:
  test_certmandb:

