PROJECT_NAME := certops
APP_NAME := certbin
APP_VERSION := $(shell cat config/version.rb | grep VERSION | cut -d "'" -f 2)
APP_REVISION := $(shell git log --pretty=format:'%h' -n 1)
APP_SOURCE := $(shell git config --get remote.origin.url)
APP_CONTEXT := ./
APP_DOCKERFILE := Dockerfile

IMAGE_REPO := quay.io/metasync/${PROJECT_NAME}-${APP_NAME}
IMAGE_TAG := ${APP_VERSION}
IMAGE_NAME := ${IMAGE_REPO}:${IMAGE_TAG}

BASE_IMAGE_REPO := docker.io/ruby
RUBY_VERSION := 3.2.1
ALPINE_VERSION := 3.17
BASE_IMAGE_TAG := ${RUBY_VERSION}-alpine${ALPINE_VERSION}

OPENAPI_SPEC_PATH := ${PWD}/document/openapi_spec

CONTAINER_CLI := docker
# CONTAINER_CLI := podman
