version: "3.6"

services:
  certbin:
    # For development only
    image: quay.io/metasync/ruby:3.2.2-alpine3.18
    depends_on:
      - certbindb
      # - certbindb.test
    environment:
      - HANAMI_ENV=development
    volumes:
      - ../:/home/app
      - ../vendor/bundle:/usr/local/bundle
    command: [ "hanami", "server" ]
    # entrypoint: /bin/sh
    # stdin_open: true
    # tty: true
