version: "3.6"

services:
  certbin:
    # For test only
    image: quay.io/metasync/ruby:3.2.2-alpine3.18
    volumes:
      - ../:/home/app
      - ../vendor/bundle:/usr/local/bundle
    entrypoint: /home/app/scripts/run-spec.sh
    # entrypoint: /bin/sh
    # stdin_open: true
    # tty: true
