version: "3.6"

services:
  certbindb:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: certbin
    volumes:
      # - dev_certbindb_psql:/var/lib/postgresql/data
      - ./data/dev_certbindb_psql:/var/lib/postgresql/data
  # certbindb.test:
  #   image: postgres:15.3-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: certbin
  #   volumes:
  #     - ./data/test_certbindb_psql:/var/lib/postgresql/data

