version: "3.6"

services:
  certbindb:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: certbin
    volumes:
      - dev_certbindb_psql:/var/lib/postgresql/data
  # certbindb.test:
  #   image: postgres:15.2-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: certbin
  #   volumes:
  #     - test_certbindb_psql:/var/lib/postgresql/data

volumes:
  dev_certbindb_psql:
  # test_certbindb_psql:
